### PR TITLE
implement segmentation method for green view score

### PR DESCRIPTION
**Pull request by banjtheman**
Created a new module to calculate GVI based on the method from the [StreetView-NatureVisibility project](https://github.com/Spatial-Data-Science-and-GEO-AI-Lab/StreetView-NatureVisibility)

README provides steps to install and run locally.

### CODE REVIEW

**Comment by danbjoseph** [comment]
- can you please resubmit this against this PR against `main`? i find it confusing to have some already merged commits showing as changes alongside the changes you've made. the branch you've submitted against is 4 commits behind `main`.
- the readme instructions should build on our existing readme. for example, we already have a "Setup" section.
- what's the purpose of including a streamlit app?
- this process should be a simple swap for our treepedia based option in [3. Assign a Green View score to each image/feature](https://github.com/AmericanRedCross/street-view-green-view?tab=readme-ov-file#3-assign-a-green-view-score-to-each-imagefeature) - when @dragonejt in #42 is tackling having 2 options for step 2, he has gone the route of including an argument for the method. that is, when running `python -m src.download_images` the user can include a `MAPILLARY` or `LOCAL` argument. similarly, for step 3 calculating green view, we may want to let users include an argument defining their preferred analysis method, something like `TREEPEDIA` or `MASK2FORMER`

**Comment by banjtheman** [comment]
* Changed to main branch
* [Streamlit](https://streamlit.io/) app provides a way to visualize how the segmentation works. It is open source and runs locally.
* This part sounds like a new feature, since we would be editing the main script and pipeline.  Let's have this PR be for integrating the standalone module. 
* We can then can create a new issue to migrate the module into the existing pipeline with the desired functionally (and the README update) (This also provides a good first issue for folks wanting to contribute!)

**Review by jayqi — CHANGES_REQUESTED** [review]
> This part sounds like a new feature, since we would be editing the main script and pipeline. Let's have this PR be for integrating the standalone module.

I think what Dan is asking for is for this code to be better integrated into the rest of the project. I get that the current implementation is standalone and self-contained, but I think if we want to merge code into the `main` branch, it should be consistent and well-integrated with the rest of the project—specifically the rest of the source code in the project's Python package that's located in `src/`.

Some specifics:

- The code in the PR should go into the `src/gvi/segmentation` submodule. 
- There should be a function implemented that matches the API from the existing [`get_gvi_score`](https://github.com/AmericanRedCross/street-view-green-view/blob/24d4159bc2d34a7687e3576e0a179a5b11bfec9c/src/assign_gvi_to_points.py#L24-L33) function. This function should take the path to a _non-segmented_ image and output the GVI score for the image. (Both the segmenting and the GVI calculation should be encapsulated in that function.) Then we can easily implement the swapping when they have the same API.
    https://github.com/AmericanRedCross/street-view-green-view/blob/24d4159bc2d34a7687e3576e0a179a5b11bfec9c/src/assign_gvi_to_points.py#L24-L33
    - I think it could be reasonable to consider the _swapping_ functionality to be a separate feature, like what you've said, in order to keep this PR smaller. 
- The requirements should be integrated into the package's requirements in `pyproject.toml`.

**Comment by dragonejt** [comment]
Agree with Jay, here's how I did something similar for image sources in #42 :

* Add a submodule for this step of the project (`src.gvi`)
* Add an interface (`AbstractBaseClass`) that both the classical GVI method and new segmentation GVI method will inherit from. Something like `src/gvi/gvi_scorer.py`, and there should at the very least be a common constructor and a `get_gvi_for_image(image_path: Path)` abstract method
* Add an Enum to select which GVI Scorer to use, and add it as a CLI argument

**Comment by danbjoseph** [comment]
this PR addresses #10

**Comment by danbjoseph** [comment]
it would also be good to save the green score from this segmentation method to a column with a specific header so that the user could run both the "pixel-counting" method and this method on the same files, end up with both result columns, and then compare.

**Comment by danbjoseph** [comment]
this is superseded by #55

**Pull request closed without merging**
